#!/usr/bin/env ruby
require "fileutils"
require "erb"

if ARGV.include? "--sync"
  system "git pull"
  exec File.expand_path(__FILE__)
end

SYSTEM = `uname`.chomp.downcase

DIR = File.dirname __FILE__

puts "\e[33;1mSyncing files\e[0m"

def sync(files)
  files.each do |from, to|
    print "\e[34;1m=> \e[0;1m#{to}\e[0m"
    from = "#{DIR}/#{from}"
    to = to.gsub(/^~/, ENV["HOME"])
    unless File.exist? from
      puts "\e[31;1m no such file!\e[0m"
      next
    end
    FileUtils.mkdir_p File.dirname to
    if from =~ /\.erb$/
      File.open(to, "w") { |f| f.write ERB.new(File.read(from)).result }
      puts "\e[32;1m erb\e[0m"
    else
      FileUtils.cp from, to
      puts "\e[32;1m cp\e[0m"
    end
  end
end

Dir["./**/sync.rb"].each do |file|
  load file
end
