syn on
set t_Co=256
colorscheme jellybeans
set modelines=3
set background=dark

set tabstop=4
set shiftwidth=4
set expandtab

set autoindent
set number
set cursorline
set laststatus=2

" kill delay when hitting esc in visual mode
set timeoutlen 100

au BufRead,BufNewFile ~/code/ruby/* setl tabstop=8 shiftwidth=4 softtabstop=4 noexpandtab
au BufRead,BufNewFile ~/code/charlie-ruby/* setl tabstop=8 shiftwidth=4 softtabstop=4 noexpandtab
au BufRead,BufNewFile ~/.rubies/.sources/* setl tabstop=8 shiftwidth=4 softtabstop=4 noexpandtab
au BufRead,BufNewFile *.rb setl tabstop=2 shiftwidth=4 softtabstop=2 expandtab

" scrolls the buffer before you reach the last line of the window
set scrolloff=3

" most useless crap ever, stops you using the alt key
set winaltkeys=no

noremap <C-up>    <C-w><up>
noremap <C-down>  <C-w><down>
noremap <C-left>  <C-w><left>
noremap <C-right> <C-w><right>

noremap <C-c> <Esc>

function! NumberToggle()
  if(&relativenumber == 1)
    set number
  else
    set relativenumber
  endif
endfunc

nnoremap <C-n> :call NumberToggle()<cr>
