syn on
set modelines=3
set background=dark

set tabstop=4
set shiftwidth=4
set expandtab

set autoindent
set number

au BufRead,BufNewFile ~/code/ruby/* setl tabstop=8 shiftwidth=4 softtabstop=4 noexpandtab
au BufRead,BufNewFile ~/code/charlie-ruby/* setl tabstop=8 shiftwidth=4 softtabstop=4 noexpandtab
au BufRead,BufNewFile *.rb setl tabstop=2 shiftwidth=4 softtabstop=2 expandtab
